# Generated by Django 3.1 on 2023-07-22 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_reviewrating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviewrating',
            old_name='Product',
            new_name='product',
        ),
    ]
